export class Gasto {
    UZFTORDERTOW_ID?: string;
   UZFTORDERTOW_NUMERO: string;
   UZFTORDERTOW_FECHA: string;
   UZFTORDERTOW_TOTAL_DIAS: number;
   UZFTORDERTOW_MES: string;
   UZFTORDERTOW_CANTIDAD: number;
   UZFTORDERTOW_PRECIO_UNITARIO: number; 
   UZFTORDERTOW_SUBTOTAL: number;
   UZFTORDERTOW_IVA: number;     
   UZFTORDERTOW_OTRO_IMPUESTO: number; 
   UZFTORDERTOW_TOTAL: number;   
   UZFTORDERTOW_INSTALACION: number; 
   UZFTORDERTOW_GASTO_AFECTUAR: number;
   UZFTORDERTOW_OTRO_GASTO_AFECTUAR: number;
   UZFTORDERTOW_SALDO: number;
   UZFTORDERTOW_OTRO_SALDO: number;
}
