export class OrdenPdf {
     UZFTEMPLOYEE_NOMBRE: String;

	 UZFTPROVIDER_NOMBRE: String;
     UZFTPROVIDER_RUC: String;
     
	 UZFTCONTRATO_OBJETO_CONTRATA: String;
     UZFTCONTRATO_NUMERO_CONTRATO: number;
     
	 UZFTCERTIFICATE_CODIGO_PRESUP: number;
	 UZFTCERTIFICATE_DESCRIPCIONPRE: String;
     UZFTCERTIFICATE_VALOR: number;
     UZFTCERTIFICATE_GASTO_AFECTUAR: number;
     UZFTCERTIFICATE_OTRO_VALOR: number;
     UZFTCERTIFICATE_OTRO_GASTOAFEC: number;

     UZFTTYPEORDER_DESCRIPCION: String;
     
	 UZFTORDER_ID: number;
	 UZFTORDER_NUMERO: number;
	 UZFTORDER_FECHA: String;
	 UZFTORDER_MES: String;
	 UZFTORDER_CANTIDAD: number;
	 UZFTORDER_PRECIO_UNITARIO: number;
	 UZFTORDER_SUBTOTAL: number;
	 UZFTORDER_IVA: number;
	 UZFTORDER_OTRO_IMPUESTO: number;
     UZFTORDER_TOTAL: number;
     UZFTORDER_INSTALACION: number;
     UZFTORDER_TOTAL_DIAS: number;
}
